// Generated by LiveScript 1.6.0
var out$ = typeof exports != 'undefined' && exports || this;
import$(out$, function(api){
  return api.extendPackage({
    devDependencies: {
      'vue-livescript-loader': '^0.0.1'
    }
  });
});
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}