// Generated by LiveScript 1.6.0
var fs;
fs = require('fs');
module.exports = function(api){
  return api.configureWebpack(function(){
    var additions;
    additions = {
      resolve: {
        extensions: ['.ls']
      },
      module: {
        rules: [{
          test: /\.ls$/,
          loader: 'babel-loader!vue-livescript-loader'
        }]
      }
    };
    if (fs.existsSync(api.resolve('./src/main.ls'))) {
      additions.entry = {
        app: './src/main.ls'
      };
    }
    return additions;
  });
};